# Generated by Django 2.2.4 on 2020-12-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vibescheck', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_songs', to='app_vibescheck.User'),
        ),
    ]
