# Generated by Django 2.2.4 on 2020-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vibescheck', '0003_song_users_who_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(related_name='playlists', to='app_vibescheck.Song'),
        ),
    ]
