# Generated by Django 2.2.4 on 2020-12-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vibescheck', '0004_playlist_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='song',
            new_name='songs',
        ),
    ]
