# Generated by Django 2.2.4 on 2020-12-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vibescheck', '0005_auto_20201227_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
